name: 'Auto Format'
description: 'Auto Format your code'
inputs:
  file-extensions:
    description: 'What file extensions to run through auto-formatter'
    required: true
  style:
    description: 'Style guide'
    required: true
  exclude-dirs:
    description: "Directories you want to exclude from being auto-formatted, relative to document root"
    required: false
    default: ""
  token:
    description: "Token for github"
    required: true
runs:
  using: 'node12'
  main: 'out/index.js'